//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/ndef/PhdcRecord.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComStSt25sdkNdefPhdcRecord")
#ifdef RESTRICT_ComStSt25sdkNdefPhdcRecord
#define INCLUDE_ALL_ComStSt25sdkNdefPhdcRecord 0
#else
#define INCLUDE_ALL_ComStSt25sdkNdefPhdcRecord 1
#endif
#undef RESTRICT_ComStSt25sdkNdefPhdcRecord

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComStSt25sdkNdefPhdcRecord_) && (INCLUDE_ALL_ComStSt25sdkNdefPhdcRecord || defined(INCLUDE_ComStSt25sdkNdefPhdcRecord))
#define ComStSt25sdkNdefPhdcRecord_

#define RESTRICT_ComStSt25sdkNdefNDEFRecord 1
#define INCLUDE_ComStSt25sdkNdefNDEFRecord 1
#include "com/st/st25sdk/ndef/NDEFRecord.h"

@class IOSByteArray;
@class JavaIoByteArrayInputStream;

@interface ComStSt25sdkNdefPhdcRecord : ComStSt25sdkNdefNDEFRecord

#pragma mark Public

- (instancetype __nonnull)initWithByteArray:(IOSByteArray *)aBuffer;

- (instancetype __nonnull)initWithByteArray:(IOSByteArray *)aApdu
                                withBoolean:(jboolean)aLC
                                   withByte:(jbyte)aMC;

- (instancetype __nonnull)initWithJavaIoByteArrayInputStream:(JavaIoByteArrayInputStream *)inputStream;

- (IOSByteArray *)getApdu;

- (jboolean)getLinkconnectedStatus;

- (jbyte)getMessageCounter;

- (IOSByteArray *)getPayload;

- (void)setApduWithByteArray:(IOSByteArray *)buffer;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

- (instancetype __nonnull)initWithComStSt25sdkNdefNDEFRecord:(ComStSt25sdkNdefNDEFRecord *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(ComStSt25sdkNdefPhdcRecord)

FOUNDATION_EXPORT void ComStSt25sdkNdefPhdcRecord_initWithByteArray_withBoolean_withByte_(ComStSt25sdkNdefPhdcRecord *self, IOSByteArray *aApdu, jboolean aLC, jbyte aMC);

FOUNDATION_EXPORT ComStSt25sdkNdefPhdcRecord *new_ComStSt25sdkNdefPhdcRecord_initWithByteArray_withBoolean_withByte_(IOSByteArray *aApdu, jboolean aLC, jbyte aMC) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkNdefPhdcRecord *create_ComStSt25sdkNdefPhdcRecord_initWithByteArray_withBoolean_withByte_(IOSByteArray *aApdu, jboolean aLC, jbyte aMC);

FOUNDATION_EXPORT void ComStSt25sdkNdefPhdcRecord_initWithByteArray_(ComStSt25sdkNdefPhdcRecord *self, IOSByteArray *aBuffer);

FOUNDATION_EXPORT ComStSt25sdkNdefPhdcRecord *new_ComStSt25sdkNdefPhdcRecord_initWithByteArray_(IOSByteArray *aBuffer) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkNdefPhdcRecord *create_ComStSt25sdkNdefPhdcRecord_initWithByteArray_(IOSByteArray *aBuffer);

FOUNDATION_EXPORT void ComStSt25sdkNdefPhdcRecord_initWithJavaIoByteArrayInputStream_(ComStSt25sdkNdefPhdcRecord *self, JavaIoByteArrayInputStream *inputStream);

FOUNDATION_EXPORT ComStSt25sdkNdefPhdcRecord *new_ComStSt25sdkNdefPhdcRecord_initWithJavaIoByteArrayInputStream_(JavaIoByteArrayInputStream *inputStream) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkNdefPhdcRecord *create_ComStSt25sdkNdefPhdcRecord_initWithJavaIoByteArrayInputStream_(JavaIoByteArrayInputStream *inputStream);

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25sdkNdefPhdcRecord)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComStSt25sdkNdefPhdcRecord")
